apiVersion: v1
kind: Pod
metadata:
  name: kucc1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "sleep 1000"]
  - name: redis
    image: redis
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "sleep 1000"]
  - name: memcached
    image: memcached
    command: ["/bin/sh", "-ec", "sleep 1000"]
  - name: hashicorp
    image: consul
    command: ["/bin/sh", "-ec", "sleep 1000"]