apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    env: 
      - name: MYSQL_ROOT_PASSWORD  
        value: password2023
  nodeSelector: 
     kubernetes.io/hostname: nodeName
    
